### ISSUE TITLE
Error: The runners input must be a comma-separated list of strings.

### ISSUE THREAD

**Issue by andremachadoCB** [classroom-resources/autograding-grading-reporter#5]
Hi everyone 👋 

I'm trying to setup the autograding reporter on my classroom workflow but regardless of what I set as the runner, I keep getting this error in the message. I have a single test that I run, so I'm giving a single runner.

I tried with

`test-id`
`test-id,`
`"test-id"`
`"test-id,"`

even with

`test-id,test-id`

And it seems it doesn't work. Would you mind telling me where I'm wrong? Here's my runner config and reporter config

```yml
- name: Run tests
      uses: classroom-resources/autograding-io-grader@v1
      id: run-pytest
      with:
        test-name: "Run pytest"
        setup-command: "pip install --upgrade pip && pip install -r ${{ env.REQUIREMENTS }}"
        command: "python -m pytest --tb=no -q ${{ env.TEST_DIR }} > /dev/null 2>&1 && echo 'passed' || echo 'failed'"
        comparison-method: exact
        expected-output: "passed"
        timeout: 300

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTEST_RESULTS: "${{ steps.run-pytest.outputs.result }}"
      with:
        runners: run-pytest,
```

Thank you!

![image](https://github.com/user-attachments/assets/488e646a-8ce7-43a0-b650-3f521c25b568)

**Comment by chadfawcett** [comment]
Hi @andremachadoCB 👋. It appears the error message is actually misleading. The actual issue is that your `env` key needs to be uppercase of your runner id plus `_RESULTS`.

```diff
- PYTEST_RESULTS: "${{ steps.run-pytest.outputs.result }}"
+ RUN-PYTEST_RESULTS: "${{ steps.run-pytest.outputs.result }}"
```

This doesn't appear to be well documented so I've [opened an issue](https://github.com/classroom-resources/autograding-grading-reporter/issues/6) to have that address in the README.

**Comment by chadfawcett** [comment]
I've also opened an issue to fix the wrong error message being displayed.

I hope this resolved your issue. I'm going to close the issue assuming it does, but please don't hesitate to re-open if my answer doesn't resolve your issues.

**Comment by andremachadoCB** [comment]
Thank you @chadfawcett!

**Comment by Qazalbash** [comment]
Hi, I am getting a similar error and a similar configuration is running on another repo. I don't understand where the problem is.

```yaml
name: Tests

on:
  push:
    branches: ["main"]
    paths:
      - "**/*.cpp"
      - "**/*.hpp"
      - ".github/workflows/classroom.yml"
permissions:
  checks: write
  actions: read
  contents: read

jobs:
  run-autograding-tests:
    runs-on: "ubuntu-22.04"
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Installing dependencies
        run: | # https://zwarrior.medium.com/install-google-test-framework-gtest-on-ubuntu-20-04-368eb6951b12
          sudo apt install libgtest-dev build-essential cmake make -y
          apt list | grep libgtest
      - name: build
        run: |
          cmake -Bbuild
          cmake --build build
      - name: Matrix Tests
        id: matrix_tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: matrix_tests
          command: env GTEST_FILTER="MatrixTest*" ctest --test-dir build -VV --progress --output-on-failure
          timeout: 1
          max-score: 10
      - name: Square Matrix Tests
        id: square_matrix_tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: square_matrix_tests
          command: env GTEST_FILTER="SquareMatrixTest*" ctest --test-dir build -VV --progress --output-on-failure
          timeout: 1
          max-score: 10
      - name: Diagonal Matrix Tests
        id: diagonal_matrix_tests
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: diagonal_matrix_tests
          command: env GTEST_FILTER="DiagonalMatrixTest*" ctest --test-dir build -VV --progress --output-on-failure
          timeout: 1
          max-score: 10
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          MATRIX_TESTS_RESULT: "${{steps.matrix_tests.outputs.result}}"
          SQUARE_MATRIX_TESTS_RESULT: "${{steps.square_matrix_tests.outputs.result}}"
          DIAGONAL_MATRIX_TESTS_RESULT: "${{steps.diagonal_matrix_tests.outputs.result}}"
        with:
          runners: matrix_tests,square_matrix_tests,diagonal_matrix_tests
```


```bash
Run classroom-resources/autograding-grading-reporter@v1
  with:
    runners: matrix_tests,square_matrix_tests,diagonal_matrix_tests
    token: ***
  env:
    MATRIX_TESTS_RESULT: eyJ[2](https://github.com/CS224-Fall2024/hw3/actions/runs/11540190313/job/32120721497#step:8:2)ZXJzaW9uIjoxLCJzdGF0dXMiOiJwYXNzIiwibWF4X[3](https://github.com/CS224-Fall2024/hw3/actions/runs/11540190313/job/32120721497#step:8:3)Njb3JlIjoxMCwidGVzdHMiOlt7Im5hbWUiOiJtYXRyaXhfdGVzdHMiLCJzdGF0dXMiOiJwYXNzIiwic2NvcmUiOjEwLCJ0ZXN0X2NvZGUiOiJlbnYgR1RFU1RfRklMVEVSPVwiTWF0cml[4](https://github.com/CS224-Fall2024/hw3/actions/runs/11540190313/job/32120721497#step:8:4)VGVzdCpcIiBjdGVzdCAtLXRlc3QtZGlyIGJ1aWxkIC1WViAtLXByb2dyZXNzIC0tb3V0cHV0LW9uLWZhaWx1cmUiLCJmaWxlbmFtZSI6IiIsImxpbmVfbm8iOjAsImR1cmF0aW9uIjo[5](https://github.com/CS224-Fall2024/hw3/actions/runs/11540190313/job/32120721497#step:8:5)NzR9XX0=
    SQUARE_MATRIX_TESTS_RESULT: eyJ2ZXJzaW9uIjoxLCJzdGF0dXMiOiJwYXNzIiwibWF4X3Njb3JlIjoxMCwidGVzdHMiOlt7Im5hbWUiOiJzcXVhcmVfbWF0cml4X3Rlc3RzIiwic3RhdHVzIjoicGFzcyIsInNjb3JlIjoxMCwidGVzdF9jb2RlIjoiZW52IEdURVNUX0ZJTFRFUj1cIlNxdWFyZU1hdHJpeFRlc3QqXCIgY3Rlc3QgLS10ZXN0LWRpciBidWlsZCAtVlYgLS1wcm9ncmVzcyAtLW91dHB1dC1vbi1mYWlsdXJlIiwiZmlsZW5hbWUiOiIiLCJsaW5lX25vIjowLCJkdXJhdGlvbiI[6](https://github.com/CS224-Fall2024/hw3/actions/runs/11540190313/job/32120721497#step:8:6)MTd9XX0=
    DIAGONAL_MATRIX_TESTS_RESULT: eyJ2ZXJzaW9uIjoxLCJzdGF0dXMiOiJwYXNzIiwibWF4X3Njb3JlIjoxMCwidGVzdHMiOlt7Im5hbWUiOiJkaWFnb25hbF9tYXRyaXhfdGVzdHMiLCJzdGF0dXMiOiJwYXNzIiwic2NvcmUiOjEwLCJ0ZXN0X2NvZGUiOiJlbnYgR1RFU1RfRklMVEVSPVwiRGlhZ29uYWxNYXRyaXhUZXN0KlwiIGN0ZXN0IC0tdGVzdC1kaXIgYnVpbGQgLVZWIC0tcHJvZ3Jlc3MgLS1vdXRwdXQtb24tZmFpbHVyZSIsImZpbGVuYW1lIjoiIiwibGluZV9ubyI6MCwiZHVyYXRpb24iOjM2fV19
The runners input must be a comma-separated list of strings.
Error: The runners input must be a comma-separated list of strings.
```
